### ISSUE TITLE
Exercise n. 5 (Every Some) does not load

### ISSUE THREAD

**Issue by franzip** [timoxley/functional-javascript-workshop#131]
Trying to load the "Every Some" exercise from the CLI menu generates this error:

```javascript
/usr/local/lib/node_modules/functional-javascript-workshop/exercises/randomizer.js:36
      word[0] = word[0].toUpperCase()
              ^
TypeError: Cannot assign to read only property '0' of Exercitation
    at /usr/local/lib/node_modules/functional-javascript-workshop/exercises/randomizer.js:36:15
    at Array.map (native)
    at Object.randomWords [as words] (/usr/local/lib/node_modules/functional-javascript-workshop/exercises/randomizer.js:35:21)
    at makeUser (/usr/local/lib/node_modules/functional-javascript-workshop/exercises/basic_every_some/exercise.js:9:18)
    at Array.map (native)
    at Object.randomArrayOf [as arrayOf] (/usr/local/lib/node_modules/functional-javascript-workshop/exercises/randomizer.js:10:71)
    at makeListOfUsers (/usr/local/lib/node_modules/functional-javascript-workshop/exercises/basic_every_some/exercise.js:14:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/functional-javascript-workshop/exercises/basic_every_some/exercise.js:17:12)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
```

**Comment by timoxley** [comment]
@tongrhj my bad! thanks!
