### ISSUE TITLE
Exercise [13] gives "missing ) after argument list" when running solution

### ISSUE THREAD

**Issue by antihero898** [timoxley/functional-javascript-workshop#155]
My program.js file:

    function repeat(operation, num){
        if (num <= 0){
            return;
        }
        operation();
        if (num % 10 === 0){
            setTimeout(functrion(){
                repeat(operation, --num);
            });
        } else {
            repeat(operation, --num);
        }
    }
    module.exports = repeat;

My Command:

`functional-javascript-workshop run program.js`

The error:

`D:\work\projects\Functional\FunctionalWorkshop>functional-javascript-workshop run program.js
? SyntaxError: missing ) after argument list
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Exercise.<anonymous> (C:\Users\ghumiston\AppData\Roaming\npm\node_modules\functional-javascript-workshop\exercises\runner.js:22:23)
    at next (C:\Users\ghumiston\AppData\Roaming\npm\node_modules\functional-javascript-workshop\node_modules\workshopper-exercise\exercise.js:182:19)
    at C:\Users\ghumiston\AppData\Roaming\npm\node_modules\functional-javascript-workshop\node_modules\workshopper-exercise\exercise.js:189:7
Could not run: missing ) after argument list`

Not sure if this is due to something I'm doing myself or not.

**Comment by antihero898** [comment]
Error on my part
