### ISSUE TITLE
Partial Application without Bind ERROR

### ISSUE THREAD

**Issue by xaca** [timoxley/functional-javascript-workshop#201]
Hello, i'm stuck in exercise 9, i got an error :warning: , could you please help. thank you!

> functional-javascript run logger.js
> fs.js:114
>     throw err;
>     ^
> 
> Error: ENOENT: no such file or directory, open '**local_path**\AppData\Local\Temp;C:\Program Files\Java\jdk1.8.0_111\bin\solution.js.input.json'
>     at Object.openSync (fs.js:438:3)
>     at Object.writeFileSync (fs.js:1189:35)
>     at Exercise.setupWrapperModule (**local_path**\AppData\Roaming\npm\node_modules\functional-javascript-workshop\exercises\runner.js:51:12)
>     at next (**local_path**\AppData\Roaming\npm\node_modules\functional-javascript-workshop\node_modules\workshopper-exercise\exercise.js:145:15)
>     at **local_path**\AppData\Roaming\npm\node_modules\functional-javascript-workshop\node_modules\workshopper-exercise\exercise.js:149:7
>     at process._tickCallback (internal/process/next_tick.js:61:11)

**Comment by timoxley** [comment]
I don't know but it's definitely very strange that it's trying to write to `local_path\AppData\Local\Temp;C:\Program Files\Java\jdk1.8.0_111\bin\`

I think maybe you have some weirdness configured in your environment regarding the temp directory?

**Comment by xaca** [comment]
@timoxley Thank you for your help. I try in another computer and works fine. I don't know what happend, because works fine until excercise 9. I have to review path variables. 🤓
