### ISSUE TITLE
TypeError: object is not a function

### ISSUE THREAD

**Issue by a-lion** [timoxley/functional-javascript-workshop#41]
In Functional Javascript's » Higher Order Functions problem, I keep getting a "TypeError: object is not a function" error.

If I simply `node` run the following version of my answer, it runs as I expect

``` javascript
function repeat(operation, num) {
    if (num > 0) { 
        operation(num);
        return repeat(operation, num-1);
    };
}

function operation(num){console.log(num)};

repeat(operation, 5);
```

But if I strip out the feedback in the operation function, thusly:

``` javascript
function repeat(operation, num) {
    if (num > 0) { 
        operation();
        return repeat(operation, num-1);
    };
}

function operation(){};

repeat(operation, 5);
```

... and run it as `functional-javascript run HOF.js`, then I get the following terminal feedback:

```
undefined:2
  repeat(input[0], input[1])
  ^
TypeError: object is not a function
    at out (eval at <anonymous> (/usr/local/lib/node_modules/functional-javascript-workshop/input.js:14:29), <anonymous>:2:3)
    at Function.module.exports.init (/usr/local/lib/node_modules/functional-javascript-workshop/input.js:41:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/functional-javascript-workshop/node_modules/workshopper/exec-wrapper.js:5:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

As I understand it, `repeat` is a function, as demonstrated in the first example.  So why am I being told it's not a function when I try to run it as  `functional-javascript run`?

**Comment by umairrafique85** [comment]
Hi!

I completed and verified all exercises till 7. All went fine, until I completed 8 and tried to run it, and it started throwing the same error. On all the files. Even the previous ones that it had verified before. e.g. for the first one I wrote:

```
function upperCaser(input) {
        return input.toUpperCase();
}

module.exports = upperCaser
```
now when I try to run or verify it, it throws the following error:
```
TypeError: input.toUpperCase is not a function
```
